export const PERMISSIONS = {
  // Vendors
  VENDORS_CREATE: 'vendors:create',
  VENDORS_READ: 'vendors:read',
  VENDORS_UPDATE: 'vendors:update',
  VENDORS_DELETE: 'vendors:delete',
  
  // Customers
  CUSTOMERS_CREATE: 'customers:create',
  CUSTOMERS_READ: 'customers:read',
  CUSTOMERS_UPDATE: 'customers:update',
  CUSTOMERS_DELETE: 'customers:delete',
  
  // Proposals
  PROPOSALS_CREATE: 'proposals:create',
  PROPOSALS_READ: 'proposals:read',
  PROPOSALS_UPDATE: 'proposals:update',
  PROPOSALS_DELETE: 'proposals:delete',
  
  // Projects
  PROJECTS_CREATE: 'projects:create',
  PROJECTS_READ: 'projects:read',
  PROJECTS_UPDATE: 'projects:update',
  PROJECTS_DELETE: 'projects:delete',
  
  // Tasks
  TASKS_CREATE: 'tasks:create',
  TASKS_READ: 'tasks:read',
  TASKS_UPDATE: 'tasks:update',
  TASKS_DELETE: 'tasks:delete',
  
  // Quotations
  QUOTATIONS_CREATE: 'quotations:create',
  QUOTATIONS_READ: 'quotations:read',
  QUOTATIONS_UPDATE: 'quotations:update',
  QUOTATIONS_DELETE: 'quotations:delete',
  
  // Invoices
  INVOICES_CREATE: 'invoices:create',
  INVOICES_READ: 'invoices:read',
  INVOICES_UPDATE: 'invoices:update',
  INVOICES_DELETE: 'invoices:delete',
  
  // Case Studies
  CASE_STUDIES_CREATE: 'case_studies:create',
  CASE_STUDIES_READ: 'case_studies:read',
  CASE_STUDIES_UPDATE: 'case_studies:update',
  CASE_STUDIES_DELETE: 'case_studies:delete',
  
  // Budget
  BUDGET_CREATE: 'budget:create',
  BUDGET_READ: 'budget:read',
  BUDGET_UPDATE: 'budget:update',
  BUDGET_DELETE: 'budget:delete',
  
  // Delivery Notes
  DELIVERY_NOTES_CREATE: 'delivery_notes:create',
  DELIVERY_NOTES_READ: 'delivery_notes:read',
  DELIVERY_NOTES_UPDATE: 'delivery_notes:update',
  DELIVERY_NOTES_DELETE: 'delivery_notes:delete',
  
  // Expenses
  EXPENSES_CREATE: 'expenses:create',
  EXPENSES_READ: 'expenses:read',
  EXPENSES_UPDATE: 'expenses:update',
  EXPENSES_DELETE: 'expenses:delete',
  
  // Admin
  USERS_MANAGE: 'users:manage',
  ROLES_MANAGE: 'roles:manage',
  SETTINGS_MANAGE: 'settings:manage',
  AUDIT_LOGS_READ: 'audit_logs:read',
} as const;

export const ROLE_PERMISSIONS = {
  superadmin: [
    ...Object.values(PERMISSIONS),
  ],
  admin: [
    PERMISSIONS.VENDORS_CREATE,
    PERMISSIONS.VENDORS_READ,
    PERMISSIONS.VENDORS_UPDATE,
    PERMISSIONS.VENDORS_DELETE,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_READ,
    PERMISSIONS.CUSTOMERS_UPDATE,
    PERMISSIONS.CUSTOMERS_DELETE,
    PERMISSIONS.PROPOSALS_CREATE,
    PERMISSIONS.PROPOSALS_READ,
    PERMISSIONS.PROPOSALS_UPDATE,
    PERMISSIONS.PROPOSALS_DELETE,
    PERMISSIONS.PROJECTS_CREATE,
    PERMISSIONS.PROJECTS_READ,
    PERMISSIONS.PROJECTS_UPDATE,
    PERMISSIONS.PROJECTS_DELETE,
    PERMISSIONS.TASKS_CREATE,
    PERMISSIONS.TASKS_READ,
    PERMISSIONS.TASKS_UPDATE,
    PERMISSIONS.TASKS_DELETE,
    PERMISSIONS.QUOTATIONS_CREATE,
    PERMISSIONS.QUOTATIONS_READ,
    PERMISSIONS.QUOTATIONS_UPDATE,
    PERMISSIONS.QUOTATIONS_DELETE,
    PERMISSIONS.INVOICES_CREATE,
    PERMISSIONS.INVOICES_READ,
    PERMISSIONS.INVOICES_UPDATE,
    PERMISSIONS.INVOICES_DELETE,
    PERMISSIONS.CASE_STUDIES_CREATE,
    PERMISSIONS.CASE_STUDIES_READ,
    PERMISSIONS.CASE_STUDIES_UPDATE,
    PERMISSIONS.CASE_STUDIES_DELETE,
    PERMISSIONS.BUDGET_CREATE,
    PERMISSIONS.BUDGET_READ,
    PERMISSIONS.BUDGET_UPDATE,
    PERMISSIONS.BUDGET_DELETE,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.AUDIT_LOGS_READ,
    PERMISSIONS.DELIVERY_NOTES_CREATE,
    PERMISSIONS.DELIVERY_NOTES_READ,
    PERMISSIONS.DELIVERY_NOTES_UPDATE,
    PERMISSIONS.DELIVERY_NOTES_DELETE,
  ],
  manager: [
    PERMISSIONS.VENDORS_READ,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_READ,
    PERMISSIONS.CUSTOMERS_UPDATE,
    PERMISSIONS.PROPOSALS_CREATE,
    PERMISSIONS.PROPOSALS_READ,
    PERMISSIONS.PROPOSALS_UPDATE,
    PERMISSIONS.PROJECTS_CREATE,
    PERMISSIONS.PROJECTS_READ,
    PERMISSIONS.PROJECTS_UPDATE,
    PERMISSIONS.TASKS_CREATE,
    PERMISSIONS.TASKS_READ,
    PERMISSIONS.TASKS_UPDATE,
    PERMISSIONS.QUOTATIONS_CREATE,
    PERMISSIONS.QUOTATIONS_READ,
    PERMISSIONS.QUOTATIONS_UPDATE,
    PERMISSIONS.INVOICES_CREATE,
    PERMISSIONS.INVOICES_READ,
    PERMISSIONS.INVOICES_UPDATE,
    PERMISSIONS.CASE_STUDIES_CREATE,
    PERMISSIONS.CASE_STUDIES_READ,
    PERMISSIONS.CASE_STUDIES_UPDATE,
    PERMISSIONS.BUDGET_READ,
    PERMISSIONS.BUDGET_UPDATE,
  ],
  staff: [
    PERMISSIONS.VENDORS_READ,
    PERMISSIONS.CUSTOMERS_READ,
    PERMISSIONS.PROPOSALS_READ,
    PERMISSIONS.PROJECTS_READ,
    PERMISSIONS.TASKS_CREATE,
    PERMISSIONS.TASKS_READ,
    PERMISSIONS.TASKS_UPDATE,
    PERMISSIONS.QUOTATIONS_READ,
    PERMISSIONS.INVOICES_READ,
    PERMISSIONS.CASE_STUDIES_READ,
    PERMISSIONS.BUDGET_READ,
  ],
  customer: [
    PERMISSIONS.PROPOSALS_READ,
    PERMISSIONS.PROJECTS_READ,
    PERMISSIONS.QUOTATIONS_READ,
    PERMISSIONS.INVOICES_READ,
    PERMISSIONS.CASE_STUDIES_READ,
  ],
  vendor: [
    PERMISSIONS.PROPOSALS_READ,
    PERMISSIONS.QUOTATIONS_CREATE,
    PERMISSIONS.QUOTATIONS_READ,
    PERMISSIONS.QUOTATIONS_UPDATE,
  ],
};

export function hasPermission(userRole: string, permission: string): boolean {
  const rolePermissions = ROLE_PERMISSIONS[userRole as keyof typeof ROLE_PERMISSIONS];
  return rolePermissions?.includes(permission) || false;
}