#!/bin/bash

echo "🚀 Simple VPS Deployment"
echo "========================"
echo "VPS: 109.199.116.107"
echo "Domain: work.smartuniit.com"
echo ""

echo "📋 Step 1: Testing basic connectivity..."
ping -c 1 109.199.116.107 > /dev/null 2>&1
if [ $? -eq 0 ]; then
    echo "✅ VPS is reachable"
else
    echo "❌ VPS is not reachable"
    exit 1
fi

echo ""
echo "📋 Step 2: Manual deployment instructions..."
echo ""
echo "Please run these commands manually on your VPS:"
echo ""
echo "1. SSH to your VPS:"
echo "   ssh root@109.199.116.107"
echo "   Password: X9mK4LpZq7GtV2Fb"
echo ""
echo "2. Once connected, run these commands:"
echo ""
echo "   # Update system"
echo "   apt update -y"
echo ""
echo "   # Install Node.js"
echo "   curl -fsSL https://deb.nodesource.com/setup_18.x | bash -"
echo "   apt-get install -y nodejs"
echo ""
echo "   # Install PM2"
echo "   npm install -g pm2"
echo ""
echo "   # Install Nginx"
echo "   apt install -y nginx"
echo ""
echo "   # Navigate to web directory"
echo "   cd /var/www"
echo ""
echo "   # Clone or update project"
echo "   if [ -d 'smartuniit-taskflow' ]; then"
echo "     cd smartuniit-taskflow"
echo "     git pull origin main"
echo "   else"
echo "     git clone https://github.com/shakeelmo/-boltAPPworkmgmt_V1.1.git smartuniit-taskflow"
echo "     cd smartuniit-taskflow"
echo "   fi"
echo ""
echo "   # Install and build"
echo "   npm install"
echo "   npm run build"
echo "   cd server && npm install && cd .."
echo ""
echo "   # Setup database"
echo "   cd server"
echo "   if [ ! -f 'database.sqlite' ]; then"
echo "     touch database.sqlite"
echo "   fi"
echo "   node initDatabase.js"
echo "   node createAdmin.js"
echo "   cd .."
echo ""
echo "   # Start with PM2"
echo "   pm2 start ecosystem.config.js"
echo "   pm2 save"
echo ""
echo "   # Configure Nginx"
echo "   systemctl reload nginx"
echo ""
echo "3. Your app will be available at: http://work.smartuniit.com"
echo "   Login: admin@example.com / admin123"
echo ""
echo "🚀 Ready to deploy! Follow the steps above."






