-- MySQL / MariaDB migration for Project Completion Reports module
CREATE TABLE IF NOT EXISTS project_completion_reports (
  id VARCHAR(191) PRIMARY KEY,
  report_number VARCHAR(50) UNIQUE,
  title VARCHAR(255),
  subtitle VARCHAR(255),
  client_name VARCHAR(255),
  client_former_name VARCHAR(255),
  client_logo LONGTEXT,
  client_rep_name VARCHAR(255),
  client_rep_designation VARCHAR(255),
  client_rep_phone VARCHAR(100),
  client_rep_email VARCHAR(255),
  contractor_name VARCHAR(255),
  contractor_logo LONGTEXT,
  submission_date VARCHAR(50),
  completion_date VARCHAR(50),
  version VARCHAR(50),
  project_location VARCHAR(255),
  project_manager VARCHAR(255),
  scope_of_work LONGTEXT,
  introduction LONGTEXT,
  scope_content LONGTEXT,
  execution_details LONGTEXT,
  testing_details LONGTEXT,
  conclusion LONGTEXT,
  photos LONGTEXT,
  signatures LONGTEXT,
  status VARCHAR(50) DEFAULT 'draft',
  created_by VARCHAR(191),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
